import { useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import type { Group } from 'three';
import type { LabDefinition } from '../../data/labCatalog';
import type { LabInputs } from '../../data/virtualLabs';
import { Box, Rod, Glass, TubeRack, Pipette, PetriDish, Microscope, Lamp, Balance, SmallPlant, Solid, GelTank, AquaticPlant, GasCollector } from './LabEquipment';
function Samples({running,value,color='#718d68',bubbles=false}:{running:boolean;value:number;color?:string;bubbles?:boolean}){const ref=useRef<Group>(null),time=useRef(0);useFrame((_,delta)=>{if(!running||!ref.current)return;time.current+=Math.min(delta,.05);ref.current.children.forEach((particle,i)=>{if(bubbles){particle.position.y=.12+(i*.047+time.current*(.04+value/280))%1;particle.position.x=Math.sin(i*9+time.current*.5)*.2;}else{const spread=.08+value/330;particle.position.x=Math.sin(i*9+time.current*.12)*spread;particle.position.z=Math.cos(i*7+time.current*.1)*spread;}});});return <group ref={ref}>{Array.from({length:24},(_,i)=><mesh key={i} position={[Math.sin(i*9)*.22,.14+(i%7)*.12,Math.cos(i*9)*.22]} scale={bubbles?[.022,.03,.022]:[.045,.025,.04]}><sphereGeometry args={[1,16,12]}/><meshPhysicalMaterial color={color} transparent opacity={.55} roughness={.12} metalness={.1}/></mesh>)}</group>;}
export default function LabScene({lab,inputs,value,running,eyepiece}:{lab:LabDefinition;inputs:LabInputs;value:number;running:boolean;eyepiece:boolean}){const engine=lab.engine;
 if(eyepiece&&engine==='microscopy')return <group rotation={[-Math.PI/2,0,0]} scale={inputs.magnification/100}>{Array.from({length:30},(_,i)=><group key={i} position={[(i%6-2.5)*.35,Math.floor(i/6)*.28-.6,0]}><mesh scale={[.16,.12,.018]}>{lab.title.toLowerCase().includes('animal')?<sphereGeometry args={[1,24,16]}/>:<boxGeometry args={[2,2,1]}/>}<meshStandardMaterial color={lab.title.toLowerCase().includes('animal')?'#c6a7b7':'#98b395'} transparent opacity={.4+inputs.stain/200} wireframe={inputs.focus<15||inputs.focus>85}/></mesh><mesh position={[.02,0,.04]} scale={[.04,.04,.025]}><sphereGeometry args={[1,16,12]}/><Solid color="#74517e"/></mesh></group>)}</group>;
 if(engine==='microscopy')return <><Microscope/><group position={[1.3,0,0]}><Box size={[.9,.05,.65]} color="#ccd9d9"/>{[0,1,2].map(i=><Box key={i} position={[i*.18-.18,.07,0]} size={[.13,.02,.5]} color="#b6cbd2"/>)}</group></>;
 if(engine==='electrophoresis')return <GelTank value={value} voltage={inputs.voltage} concentration={inputs.substrate}/>;
 if(engine==='ecology'||engine==='inheritance')return <><Box position={[0,.04,0]} size={[2.7,.08,1.8]} color="#726b50"/>{Array.from({length:engine==='ecology'?Math.max(1,Math.round(inputs.density/8)):8},(_,i)=><group key={i} position={[(i%4-.5)*.55-.6,.08,Math.floor(i/4)*.5-.5]} scale={.5}><SmallPlant/></group>)}{[-1,1].map(i=><group key={i}><Rod position={[i*1.3,.15,0]} height={1.8} rotation={[Math.PI/2,0,0]} color="#d9d5b1"/><Rod position={[0,.15,i*.9]} height={2.6} rotation={[0,0,Math.PI/2]} color="#d9d5b1"/></group>)}</>;
 if(engine==='germination')return <PetriDish>{Array.from({length:7},(_,i)=><group key={i} position={[Math.sin(i*7)*.45,.15,Math.cos(i*7)*.45]}><mesh scale={[.07,.05,.11]}><sphereGeometry args={[1,20,12]}/><Solid color="#c2ab75"/></mesh><Rod position={[0,.05+value/300,0]} height={.02+value/150} radius={.013} color="#87a47a"/></group>)}</PetriDish>;
 if(engine==='chromatography')return <><Glass radius={.55} height={1.4} fill={.14}/><Box position={[0,.8,0]} size={[.4,1.1,.018]} color="#e4dece"/>{['#aa9c5b','#668c72','#b585a0'].map((color,i)=><Box key={color} position={[0,.33+Math.min(1,inputs.duration/30)*(value/110)*(i+1)*.3,.025]} size={[.35,.025,.015]} color={color}/>)}</>;
 if(engine==='enzymes')return <><TubeRack fill={inputs.substrate/220+.1}/><group position={[1.25,1,0]}><Pipette/></group><Samples running={running} value={value}/></>;
 if(engine==='osmosis')return <><group position={[-.65,0,0]}><Glass fill={.55}/><Box position={[0,.45,0]} size={[.17,.6,.15]} color="#d1c697"/></group><group position={[.65,0,0]}><Glass fill={.55}/><Box position={[0,.45,0]} size={[.17*value/100,.6,.15]} color="#d1c697"/></group><group position={[1.7,0,0]}><Balance/></group></>;
 if(engine==='transpiration')return <><SmallPlant/><Rod position={[.6,.3,0]} height={1.4} radius={.04} rotation={[0,0,Math.PI/2]} color="#bdccd1"/><mesh position={[.1+value/130,.3,.03]}><sphereGeometry args={[.055,20,12]}/><Solid color="#e1e8de"/></mesh><group position={[1.5,0,0]}><Glass radius={.3} height={.8} fill={.5}/></group></>;
 if(engine==='respiration')return <><Glass radius={.45} height={1.1} fill={.2} color="#cbc0a1"/><Box position={[0,1.12,0]} size={[.9,.08,.9]} color="#839490"/><Rod position={[.7,1.15,0]} height={1.3} rotation={[0,0,Math.PI/2]} radius={.025}/><mesh position={[.3+value/170,1.15,.02]}><sphereGeometry args={[.035,16,10]}/><Solid color="#b97983"/></mesh></>;
 if(engine==='water-quality')return <><TubeRack color={inputs.ph<6?'#bd936c':inputs.ph>8?'#8a9fae':'#91aa8c'}/><group position={[1.3,.25,0]}><Box size={[.5,.5,.25]} color="#d5dddd"/><Box position={[0,0,.14]} size={[.3,.16,.02]} color="#314a54"/></group><Rod position={[.7,.7,0]} height={.8} color="#596b76"/></>;
 return <><Glass radius={.55} height={1.25} fill={.7}/>{engine==='photosynthesis'?<><group position={[0,.1,0]}><AquaticPlant/><GasCollector response={value}/></group><group position={[-1.2,0,0]}><Lamp light={inputs.light}/></group><Samples running={running} value={value} color="#c2dadd" bubbles/></>:<Samples running={running} value={value} color="#8c729a"/>}<group position={[1.3,.8,0]}><Pipette/></group></>;
}
