import { useEffect } from 'react';
import { useAtlasStore } from '../store/atlasStore';
import { anatomy, isWithin } from '../data/anatomyTree';
import { anatomyModels } from '../data/modelRegistry';
type Tool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};
export function useAtlasTools(){useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const abort=new AbortController();
 const tools:Tool[]=[{name:'read_atlas_state',title:'Read atlas state',description:'Read current selection, visible layers, and explosion amount.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>{const s=useAtlasStore.getState();return{model:s.activeModel,selected:s.selectedId,mode:s.mode,layers:s.visibleLayers,explosion:s.explosion};}},
 {name:'select_anatomy',title:'Select an anatomy structure',description:'Select and focus a structure in the currently open atlas.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{const {id}=(input??{}) as {id?:string};const s=useAtlasStore.getState();if(!id||!anatomy[id]||!isWithin(id,anatomyModels[s.activeModel].root))throw new Error('Unknown structure in the current atlas');s.select(id);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return{selected:useAtlasStore.getState().selectedId};}},
 {name:'set_anatomy_explosion',title:'Set anatomy explosion',description:'Set schematic component separation, from 0 assembled to 1 exploded.',inputSchema:{type:'object',properties:{amount:{type:'number',minimum:0,maximum:1}},required:['amount'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{const {amount}=(input??{}) as {amount?:number};if(typeof amount!=='number'||!Number.isFinite(amount)||amount<0||amount>1)throw new Error('amount must be between 0 and 1');useAtlasStore.getState().setExplosion(amount);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return{explosion:useAtlasStore.getState().explosion};}}];
 for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:abort.signal})).catch(e=>{if(!abort.signal.aborted)console.warn('Atlas tool registration failed',e);});}catch(e){console.warn('Atlas tool registration failed',e);}}
 return()=>abort.abort();},[]);}
