import { Component, Suspense, useEffect, useMemo, useRef, useState, type RefObject, type ReactNode } from 'react';
import { Canvas, useFrame, useThree, type ThreeEvent } from '@react-three/fiber';
import { AdaptiveDpr, Environment, Lightformer, OrbitControls, useGLTF, useProgress } from '@react-three/drei';
import { Box3, Color, MathUtils, Mesh, MeshStandardMaterial, Vector3 } from 'three';
import { clone } from 'three/examples/jsm/utils/SkeletonUtils.js';
import { anatomy, isWithin } from '../../data/anatomyTree';
import { anatomyModels } from '../../data/modelRegistry';
import { publicUrl } from '../../utils/basePath';
import { mapMeshToAnatomy } from '../../utils/meshMapping';
import { twinSystems, type TwinState, type TwinSystem } from '../../data/digitalTwin';
const modelUrl=publicUrl(anatomyModels.body.urls[0]);
export function meshSystem(id:string):TwinSystem|null{const node=anatomy[id];if(!node)return null;if(isWithin(id,'heart')||['arteries','veins','circulatory'].includes(node.layer))return 'heart';if(isWithin(id,'lungs')||['trachea','bronchi','diaphragm'].includes(id))return 'lungs';if(node.layer.startsWith('muscles'))return 'muscles';if(node.layer==='nervous'||isWithin(id,'brain'))return 'nervous';return node.layer==='skin'?'heat':null;}
type Props={clock:RefObject<TwinState>;selected:TwinSystem;onSelect:(system:TwinSystem)=>void;focus:number;skin:boolean;isolate:boolean;onReady:()=>void};
function Human({clock,selected,onSelect,focus,skin,isolate,onReady}:Props){
 const asset=useGLTF(modelUrl,publicUrl('/draco/'));const {camera}=useThree();const controls=useRef<React.ComponentRef<typeof OrbitControls>>(null),moving=useRef(false),destination=useRef(new Vector3()),target=useRef(new Vector3());
 const {scene,records,scale,center}=useMemo(()=>{const scene=clone(asset.scene),config=anatomyModels.body;scene.rotation.set(...config.gltfTransform.rotation);scene.scale.setScalar(config.gltfTransform.scale);scene.updateMatrixWorld(true);const bounds=new Box3().setFromObject(scene),scale=6/Math.max(...bounds.getSize(new Vector3()).toArray()),center=bounds.getCenter(new Vector3()).multiplyScalar(-scale);const records:{mesh:Mesh;id:string;system:TwinSystem|null;base:Vector3;baseScale:Vector3;pivot:Vector3;materials:MeshStandardMaterial[];colors:Color[];opacity:number;intimate:boolean}[]=[];
 scene.traverse(object=>{if(!(object instanceof Mesh))return;const id=mapMeshToAnatomy(object)??'body',materials=(Array.isArray(object.material)?object.material:[object.material]).map(m=>m.clone() as MeshStandardMaterial);object.material=Array.isArray(object.material)?materials:materials[0];object.geometry.computeBoundingBox();const layer=anatomy[id]?.layer;const opacity=layer==='skeleton'?.58:layer?.startsWith('muscles')?.2:layer==='skin'?.04:.9;const intimate=/reproduct|penis|testes|scrot|prostate|vulva/i.test(`${id} ${object.name} ${anatomy[id]?.system}`);object.userData.twinId=id;records.push({mesh:object,id,system:meshSystem(id),base:object.position.clone(),baseScale:object.scale.clone(),pivot:object.geometry.boundingBox?.getCenter(new Vector3())??new Vector3(),materials,colors:materials.map(m=>m.color.clone()),opacity,intimate});});return {scene,records,scale,center};},[asset]);
 useEffect(()=>{onReady();return()=>records.forEach(r=>r.materials.forEach(m=>m.dispose()));},[records,onReady]);
 useEffect(()=>{scene.parent?.updateWorldMatrix(true,true);const bounds=new Box3();if(focus&&selected!=='heat'){for(const record of records)if(record.system===selected&&!record.intimate&&(selected!=='heart'||isWithin(record.id,'heart'))&&(selected!=='nervous'||isWithin(record.id,'brain')))bounds.union(new Box3().setFromObject(record.mesh));}if(bounds.isEmpty()||!focus){target.current.set(0,0,0);destination.current.set(0,.1,10.7);}else{bounds.getCenter(target.current);const size=bounds.getSize(new Vector3());destination.current.copy(target.current).add(new Vector3(0,0,Math.max(2.1,Math.max(size.x,size.y)*2.5)));}moving.current=true;},[selected,focus,records,scene]);
 const tint=useMemo(()=>new Color('#8fbeca'),[]),warm=useMemo(()=>new Color('#b97455'),[]),offset=useMemo(()=>new Vector3(),[]);
 useFrame((_,dt)=>{const state=clock.current;const beat=1-.065*Math.pow(Math.max(0,Math.sin(state.heartPhase*Math.PI*2)),4),breath=1+.04*Math.sin(state.breathPhase*Math.PI*2);for(const r of records){const opacity=r.intimate?0:isolate&&r.system!==selected?.025:r.system==='heat'?(skin?.045:0):r.opacity;
 r.mesh.visible=opacity>.001;r.materials.forEach((m,i)=>{m.opacity=MathUtils.damp(m.opacity,opacity,7,Math.min(dt,.05));const transparent=m.opacity<.98;if(m.transparent!==transparent){m.transparent=transparent;m.needsUpdate=true;}m.depthWrite=!transparent;m.color.copy(r.colors[i]);if(r.system==='muscles')m.color.lerp(warm,(state.demand-1)/7*.16);if(r.system===selected)m.color.lerp(tint,.12);});
 const factor=r.system==='heart'&&isWithin(r.id,'heart')?beat:r.system==='lungs'&&isWithin(r.id,'lungs')?breath:1;r.mesh.scale.copy(r.baseScale).multiplyScalar(factor);offset.copy(r.baseScale).sub(r.mesh.scale).multiply(r.pivot).applyQuaternion(r.mesh.quaternion);r.mesh.position.copy(r.base).add(offset);
 }if(moving.current&&controls.current){camera.position.lerp(destination.current,1-Math.exp(-dt*3));controls.current.target.lerp(target.current,1-Math.exp(-dt*3));controls.current.update();if(camera.position.distanceTo(destination.current)<.015)moving.current=false;}});
 function select(event:ThreeEvent<MouseEvent>){if(event.delta>4)return;const id=event.object.userData.twinId,system=meshSystem(id);if(system){event.stopPropagation();onSelect(system);}}
 return <><group scale={scale} position={center}><primitive object={scene} onClick={select}/></group><OrbitControls ref={controls} makeDefault minDistance={1.2} maxDistance={16} enableDamping onStart={()=>{moving.current=false;}}/></>;
}
class ViewerBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}componentDidCatch(error:Error){console.error('[Digital Twin] Anatomy load failed',error);}render(){return this.state.failed?<div className="twin-load" role="alert"><strong>3D anatomy could not load</strong><p>Check your connection and WebGL support.</p><button onClick={()=>{useGLTF.clear(modelUrl);this.setState({failed:false});}}>Retry 3D model</button></div>:this.props.children;}}
function Progress({ready}:{ready:boolean}){const {progress}=useProgress();return !ready?<div className="twin-load" role="status"><span className="twin-loading-orbit"/><strong>Preparing the living human</strong><span>{Math.round(progress)}% · loading anatomy and materials</span></div>:null;}
export default function TwinViewer(props:Omit<Props,'onReady'>){const [ready,setReady]=useState(false);const readyCallback=useMemo(()=>()=>setReady(true),[]);return <div className="twin-scene" aria-label="Interactive 3D living human model"><ViewerBoundary><Canvas dpr={[1,1.5]} camera={{position:[0,.1,10.7],fov:38,near:.01,far:100}} gl={{antialias:true,powerPreference:'high-performance'}}><color attach="background" args={['#101c25']}/><ambientLight intensity={.6}/><hemisphereLight args={['#d3e7f1','#72685b',.85]}/><directionalLight position={[3,4,6]} intensity={2.1}/><directionalLight position={[-3,2,3]} intensity={.9}/><Environment resolution={128} frames={1}><Lightformer intensity={1.3} position={[4,3,4]} scale={[4,6,1]} target={[0,0,0]}/><Lightformer intensity={.8} position={[-4,1,-3]} scale={[3,4,1]} target={[0,0,0]}/></Environment><Suspense fallback={null}><Human {...props} onReady={readyCallback}/></Suspense><AdaptiveDpr/></Canvas><Progress ready={ready}/></ViewerBoundary><div className="twin-scene-label"><span className="twin-dot"/> MULTI-SYSTEM ANATOMY<span>{twinSystems.find(s=>s.id===props.selected)?.name}</span></div><div className="twin-scene-help">Drag to rotate · Scroll to zoom · Click a system to inspect</div></div>;}
