import { SimulationExplanation } from '../controls/SimulationControls';
import { useState } from 'react';
import MovementLesson from '../atlas/MovementLesson';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowRight, ArrowUpRight, Crosshair, EyeOff, Focus, Layers3, MapPin, RotateCcw, ScanLine, Undo2, X } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { anatomy, isWithin } from '../../data/anatomyTree';
import { useAtlasStore } from '../../store/atlasStore';
import { anatomyModels, modelRoute } from '../../data/modelRegistry';
export default function RightPanel({open,onClose}:{open:boolean;onClose:()=>void}){
 const [movement,setMovement]=useState(false);const navigate=useNavigate();const s=useAtlasStore();const choose=(id:string)=>{if(isWithin(id,anatomyModels[s.activeModel].root))s.select(id);else navigate(`/atlas/body/${id}`);};const n=anatomy[s.selectedId]??anatomy.body;const dedicated=Object.values(anatomyModels).find(m=>m.root===n.id&&m.root!=='body'&&!m.systemId);const related=n.relatedStructures??(n.parent?anatomy[n.parent].children.filter(id=>id!==n.id):[]);
 return <aside className={`right-panel ${open?'panel-open':''}`} aria-label="Selected anatomy information"><div className="info-top"><span className="panel-eyebrow">{s.learn?'LEARN MODE':'STRUCTURE DETAILS'}</span><button className="icon-btn panel-close" onClick={onClose} aria-label="Close structure information"><X size={17}/></button></div><SimulationExplanation/><AnimatePresence mode="wait"><motion.div key={n.id} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:.18}} className="info-content"><div className="structure-symbol"><Layers3 size={28} strokeWidth={1.2}/></div><span className="system-pill">{n.system}</span><h2>{s.learningLevel==='basic'?n.simpleName??n.name:n.name}</h2>{s.learningLevel!=='basic'&&<p className="scientific-name">{n.scientificName}</p>}<div className="location"><MapPin size={14}/><span>{n.location}{n.depth?` · ${n.depth} layer`:''}</span></div>
 <div className="info-section"><h3>{s.learn?'What is it?':'Overview'}</h3><p>{s.learningLevel==='basic'?n.simpleDescription??n.description:n.description}</p></div>
 {n.functions.length>0&&<div className="info-section learn-functions"><h3>{s.learn?'What does it do?':'Primary functions'}</h3><ul>{n.functions.slice(0,s.learningLevel==='basic'?1:undefined).map(f=><li key={f}>{f}</li>)}</ul></div>}
 {n.type==='muscle'&&<button className="details-toggle" aria-expanded={s.learningLevel==='advanced'} onClick={()=>s.set('learningLevel',s.learningLevel==='advanced'?'standard':'advanced')}>{s.learningLevel==='advanced'?'Use standard explanation':'View advanced anatomy'}<ArrowRight size={13}/></button>}
 {(s.learningLevel==='advanced')&&<div className="anatomy-specific-info">{([['Origin',n.origin],['Insertion',n.insertion],['Innervation',n.innervation],['Blood supply',n.bloodSupply]] as const).filter(([,value])=>value).map(([label,value])=><div className="info-section" key={label}><h3>{label}</h3><p>{value}</p></div>)}{n.type==='muscle'&&!n.origin&&!n.insertion&&<p className="pending-detail">Detailed attachments and innervation coming soon.</p>}{n.articulations&&<div className="info-section"><h3>Articulations</h3><p>{n.articulations.join(', ')}</p></div>}{n.landmarks&&<div className="info-section"><h3>Major landmarks</h3><p>{n.landmarks.join(', ')}</p></div>}</div>}
 {n.attachments&&<div className="attachment-controls"><button aria-pressed={s.showAttachments} onClick={()=>s.set('showAttachments',!s.showAttachments)}>Show Attachments</button><small>Markers indicate associated bone regions; precise attachment surfaces require authored assets.</small></div>}{n.id.startsWith('biceps-brachii')&&<button className="outline-btn" onClick={()=>setMovement(true)}>Show Action</button>}{movement&&<MovementLesson onClose={()=>setMovement(false)}/>}<div className="structure-actions"><button onClick={()=>s.command('focus',n.id)}><Crosshair size={17}/> Focus</button><button className={s.isolation?'active':''} onClick={()=>s.setMode(s.isolation?'normal':'isolate')}><Focus size={17}/> {s.isolation?'Show all':'Isolate'}</button><button className={s.hiddenIds.includes(n.id)?'active':''} onClick={()=>s.hide(n.id)}><EyeOff size={17}/> {s.hiddenIds.includes(n.id)?'Show':'Hide / Peel'}</button><button className={s.transparentIds.includes(n.id)?'active':''} onClick={()=>s.transparent(n.id)}><ScanLine size={17}/> Transparent</button></div><div className="peel-actions"><button disabled={!s.peelHistory.length} onClick={s.undoPeel}><Undo2 size={14}/> Undo peel</button><button onClick={s.reset}><RotateCcw size={14}/> Reset anatomy</button></div><button className={`explode-action ${s.explosion>0?'active':''}`} onClick={()=>s.setExplosion(s.explosion>0?0:.65)}><Layers3 size={17}/>{s.explosion>0?'Assemble structures':s.systemFilter==='muscular'?'Explode muscles':'Explode anatomy'}<ArrowRight size={16}/></button>
 {n.children.length>0&&<div className="info-section substructures"><h3>Explore substructures <span>{n.children.length}</span></h3>{n.children.map(id=><button key={id} onClick={()=>choose(id)}>{anatomy[id].name}<ArrowUpRight size={14}/></button>)}</div>}
 {(s.learningLevel!=='basic')&&related.length>0&&<div className="info-section"><h3>Related structures</h3><div className="related-links">{related.slice(0,8).filter(id=>anatomy[id]).map(id=><button key={id} onClick={()=>choose(id)}>{anatomy[id].name}</button>)}</div></div>}
 {n.parent&&<button className="parent-link" onClick={()=>choose(n.parent!)}>Parent: {anatomy[n.parent].name}</button>}
 {dedicated&&s.activeModel!==dedicated.id&&<Link className="dedicated-link" to={modelRoute(dedicated)}>Open dedicated {n.name.toLowerCase()} atlas <ArrowUpRight size={16}/></Link>}{n.source&&<a className="reference-link" href={n.source} target="_blank" rel="noreferrer">Educational reference <ArrowUpRight size={13}/></a>}
 <p className="info-disclaimer">{s.modelStatus==='ready'?'Educational anatomy visualization.':s.developerFallback?'Development Anatomy Model · Schematic geometry, not medical-quality anatomy.':'A licensed anatomical model is required for this asset slot.'}</p>
 </motion.div></AnimatePresence></aside>;
}

