import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowRight, Dna, FlaskConical, Leaf, PawPrint, Search } from 'lucide-react';
import { biologyModules, biologySubjects, classMap } from '../data/biology';
import { virtualLabs } from '../data/virtualLabs';
import '../styles/biology.css';

export default function Biology(){const [query,setQuery]=useSearchParams(),[search,setSearch]=useState(''),[page,setPage]=useState(0);const grade=Number(query.get('class'))||0,subject=query.get('subject')??'all';const words=search.toLowerCase().trim().split(/\s+/).filter(Boolean);const results=biologyModules.filter(module=>(!grade||module.classLevel===grade)&&(subject==='all'||module.subject===subject)&&words.every(word=>`${module.title} ${module.overview} ${module.explanation} ${module.subject}`.toLowerCase().includes(word)));function exportCoverage(){const blob=new Blob([JSON.stringify({version:1,boards:['CBSE / NCERT','ICSE / ISC','Andhra Pradesh','Enrichment'],alignmentStatus:'Provisional; chapter-level audit pending',classes:classMap.map(item=>({class:item.classLevel,count:item.modules.length,modules:item.modules.map(module=>({id:module.id,title:module.title,subject:module.subject,boardMappingStatus:'Unverified'}))}))},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='visionaries-biology-coverage.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}function filter(key:string,value:string){const next=new URLSearchParams(query);if(value==='all')next.delete(key);else next.set(key,value);setQuery(next);setPage(0);}
 return <main id="main" className="biology-page"><header className="bio-hero"><div className="eyebrow">VISIONARIESAI LABS · BIOLOGY & LABS</div><h1>Life, at every scale.</h1><p>Explore plants and animals. Decode genetic information. Investigate ideas through virtual experiments.</p><div className="bio-stat-row"><span><Leaf size={18}/> Plant & animal explorers</span><span><Dna size={18}/> Genetics & molecules</span><Link to="/labs"><FlaskConical size={18}/> {virtualLabs.length} virtual laboratories <ArrowRight size={14}/></Link></div></header>
 <nav className="bio-subjects" aria-label="Biology subjects">{['all',...biologySubjects].map(item=><button key={item} aria-pressed={subject===item} onClick={()=>filter('subject',item)}>{item==='all'?'All biology':item}</button>)}<Link to="/labs">Virtual laboratories <ArrowRight size={15}/></Link></nav>
 <section className="bio-curriculum" aria-label="Classes 1 to 12 learning map"><div className="bio-section-heading"><div><div className="eyebrow">CLASSES 1–12</div><h2>A learning path that grows with you.</h2></div><button onClick={()=>filter('class','all')}>All classes</button></div><p>Suggested progression from observation to molecular reasoning. This is an adaptable learning map, not certified alignment with a specific school board.</p><details className="bio-notebook"><summary>Board coverage and verification</summary><p>Combined topic inventory for CBSE / NCERT, ICSE / ISC, Andhra Pradesh and general enrichment. Board-specific chapter mappings are provisional: this collection is not a verified exhaustive syllabus for every board or academic year.</p><p>{biologyModules.length} lessons across 12 classes. The lesson cards include concise teaching prompts; many use shared comparison scenes rather than dedicated topic models.</p><button onClick={exportCoverage}>Export complete coverage inventory</button></details><div className="bio-class-grid">{classMap.map(item=><button key={item.classLevel} aria-pressed={grade===item.classLevel} onClick={()=>filter('class',String(item.classLevel))}><strong>Class {item.classLevel}</strong><small>{item.band}</small><span>{item.modules.length} modules</span></button>)}</div></section>
 <section className="bio-module-section"><div className="bio-section-heading"><h2>{grade?`Class ${grade} learning modules`:'Explore the biology library'}</h2><label className="bio-search"><Search size={17}/><input aria-label="Search biology modules" placeholder="Search biology modules…" value={search} onChange={event=>{setSearch(event.target.value);setPage(0);}}/></label></div><p role="status">{results.length} modules · {subject==='all'?'All subjects':subject}</p><div className="bio-card-grid">{results.slice(page*24,page*24+24).map(module=><Link className="bio-module-card" key={module.id} to={`/biology/module/${module.id}`}><div className="bio-card-icon">{module.subject==='Plant biology'?<Leaf size={30}/>:module.subject==='Animal biology'?<PawPrint size={30}/>:<Dna size={30}/>}<span>CLASS {module.classLevel}</span></div><small>{module.subject}</small><h3>{module.title}</h3><p>{module.overview}</p><span className="bio-card-action">Open interactive lesson <ArrowRight size={16}/></span></Link>)}</div><div className="bio-trial-actions"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1} of {Math.max(1,Math.ceil(results.length/24))}</span><button disabled={(page+1)*24>=results.length} onClick={()=>setPage(p=>p+1)}>Next</button></div>{!results.length&&<div className="bio-empty"><h3>No modules match these filters</h3><button onClick={()=>{setQuery({});setSearch('');}}>Reset search and filters</button></div>}</section>
 <section className="bio-lab-entry"><div><div className="eyebrow">PREDICT · CHANGE · OBSERVE · EXPLAIN</div><h2>Your virtual science bench.</h2><p>Control variables, compare trials and export your observation notebook.</p></div><Link to="/labs" className="primary-btn">Open virtual laboratories <ArrowRight size={17}/></Link></section>
 <div className="bio-lab-links">{virtualLabs.slice(0,4).map(lab=><Link key={lab.id} to={`/labs/${lab.id}`}>{lab.title}<ArrowRight size={14}/></Link>)}</div>
 </main>;
}
