import { useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { Activity, ArrowRight, Brain, Heart, Maximize, Pause, Play, RotateCcw, Thermometer, Wind, ZoomIn } from 'lucide-react';
import TwinViewer from '../components/digitalTwin/TwinViewer';
import TwinHistory from '../components/digitalTwin/TwinHistory';
import { useDigitalTwin } from '../hooks/useDigitalTwin';
import { activityPresets, twinFlow, twinSystems, type TwinSystem } from '../data/digitalTwin';
import { publicUrl } from '../utils/basePath';
import '../styles/digitalTwin.css';
const icons={heart:Heart,lungs:Wind,muscles:Activity,heat:Thermometer,nervous:Brain};
export default function DigitalTwin(){const twin=useDigitalTwin(),[selected,setSelected]=useState<TwinSystem>('heart'),[focus,setFocus]=useState(0),[skin,setSkin]=useState(false),[isolate,setIsolate]=useState(false),[tab,setTab]=useState<'biology'|'model'>('biology'),[notice,setNotice]=useState('');const root=useRef<HTMLElement>(null);const system=twinSystems.find(item=>item.id===selected)!;
 function select(id:TwinSystem){setSelected(id);setTab('biology');}
 function exportData(){const rows=['Simulation seconds,Activity percent,Heart rate bpm,Breaths per minute,Muscle demand relative,Heat production relative,Heat load index',...twin.history.map(s=>[s.seconds,s.activity,s.heartRate,s.breathingRate,s.demand,s.heatProduction,s.heatLoad*100].map(n=>n.toFixed(3)).join(','))];const url=URL.createObjectURL(new Blob([rows.join('\r\n')],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='visionaries-digital-twin-teaching-results.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await root.current?.requestFullscreen();}catch{setNotice('Fullscreen is unavailable in this browser.');}}
 const cards=[{id:'heart' as const,name:'Heart rate',value:twin.state.heartRate.toFixed(0),unit:'bpm',base:'Teaching baseline 72 bpm'},{id:'lungs' as const,name:'Breathing rate',value:twin.state.breathingRate.toFixed(0),unit:'breaths/min',base:'Teaching baseline 14/min'},{id:'muscles' as const,name:'Muscle oxygen demand',value:twin.state.demand.toFixed(1),unit:'× resting',base:'Relative demand index'},{id:'heat' as const,name:'Heat production',value:twin.state.heatProduction.toFixed(1),unit:'× resting',base:'Relative production index'}];
 return <main id="main" className="digital-twin" ref={root}><header className="twin-heading"><div><div className="eyebrow">VISIONARIESAI LABS · BIOLOGY DIGITAL TWIN</div><h1>Explore a living virtual human.</h1><p>Change the activity. See the whole body respond.</p></div><span className="twin-teaching-badge">EDUCATIONAL SIMULATION</span></header><div className="twin-metrics">{cards.map(card=>{const Icon=icons[card.id];return <button key={card.id} aria-pressed={selected===card.id} onClick={()=>select(card.id)} style={{'--signal':twinSystems.find(s=>s.id===card.id)!.color} as React.CSSProperties}><span><Icon size={17}/>{card.name}</span><strong>{card.value}<small>{card.unit}</small></strong><small>{card.base}</small></button>;})}</div>
 <div className="twin-workspace"><aside className="twin-controls"><div className="eyebrow">SCENARIO CONTROL</div><h2>From rest to motion.</h2><p>Choose an activity for this illustrative adult model.</p><div className="twin-presets">{activityPresets.map(preset=><button key={preset.name} aria-pressed={twin.activity===preset.value} onClick={()=>twin.setActivity(preset.value)}>{preset.name}<span>{preset.value}%</span></button>)}</div><label className="twin-slider">Exercise intensity <strong>{twin.activity}%</strong><input aria-label="Exercise intensity" type="range" min={0} max={100} value={twin.activity} onChange={e=>twin.setActivity(Number(e.target.value))}/><small>Activity setting, not a measured workload</small></label><div className="twin-play"><button className="primary-btn" onClick={()=>twin.running?twin.pause():twin.setRunning(true)}>{twin.running?<Pause size={16}/>:<Play size={16}/>} {twin.running?'Pause & inspect':'Start simulation'}</button><button aria-label="Reset digital twin" title="Reset digital twin" onClick={()=>{twin.reset();setFocus(0);setIsolate(false);}}><RotateCcw size={17}/></button></div><button className="twin-recovery" onClick={()=>{twin.setActivity(0);twin.setRunning(true);}}>Begin recovery <ArrowRight size={15}/></button><div className="twin-time"><span>{twin.running?'RUNNING':'PAUSED'}</span><output aria-label="Simulation time">{Math.floor(twin.state.seconds/60).toString().padStart(2,'0')}:{Math.floor(twin.state.seconds%60).toString().padStart(2,'0')}</output></div><label className="twin-speed">Simulation speed<select aria-label="Simulation speed" value={twin.speed} onChange={e=>twin.setSpeed(Number(e.target.value))}><option value={.5}>0.5×</option><option value={1}>1×</option><option value={2}>2×</option></select></label><hr/><h3>Visible anatomy</h3><label className="twin-check"><input type="checkbox" checked={skin} onChange={e=>setSkin(e.target.checked)}/> Transparent body envelope</label><label className="twin-check"><input type="checkbox" checked={isolate} onChange={e=>setIsolate(e.target.checked)}/> Isolate selected system</label><div className="twin-view-actions"><button onClick={()=>setFocus(n=>n+1)}><ZoomIn size={14}/> Focus system</button><button onClick={()=>{setFocus(0);setIsolate(false);}}>Fit human</button><button aria-label="Fullscreen digital twin" onClick={fullscreen}><Maximize size={15}/></button></div>{notice&&<p role="status">{notice}</p>}</aside>
 <TwinViewer clock={twin.clock} selected={selected} onSelect={select} focus={focus} skin={skin} isolate={isolate}/>
 <aside className="twin-inspector"><div className="eyebrow">EXAMINE THE CONNECTIONS</div><nav aria-label="Inspect organ systems">{twinSystems.map(item=>{const Icon=icons[item.id];return <button key={item.id} title={item.name} aria-label={item.name} aria-pressed={selected===item.id} onClick={()=>select(item.id)}><Icon size={19}/></button>;})}</nav><div className="twin-system-name" style={{borderColor:system.color}}><small>{system.subtitle}</small><h2>{system.name}</h2></div><div className="twin-tabs"><button aria-pressed={tab==='biology'} onClick={()=>setTab('biology')}>Underlying biology</button><button aria-pressed={tab==='model'} onClick={()=>setTab('model')}>Model details</button></div>{tab==='biology'?<><p>{system.explanation}</p><div className="twin-connection"><small>CAUSAL PATHWAY</small><p>{system.connections}</p></div><h3>Pause and investigate</h3><p>{system.observe}</p></>:<><h3>Transparent teaching rules</h3><p>Activity raises demand toward 1 + 7 × activity fraction. A demand-derived drive sets targets for heart rate (72 + 100 × drive) and breathing (14 + 30 × drive), with a small heat-load contribution. Responses approach targets gradually.</p><p>Heat production rises toward 1 + 8 × drive. Heat load accumulates from production and clears through a simple linear term. These coefficients and response times are authored teaching choices, not fitted measurements.</p><p>Relative flow uses heart rate × illustrative stroke volume, normalized to the resting baseline. No pressure, gas concentrations or individual prediction is calculated.</p></>}<div className="twin-secondary-metrics"><div><span>Relative flow</span><strong>{twinFlow(twin.state).toFixed(1)}×</strong></div><div><span>Heat load index</span><strong>{(twin.state.heatLoad*100).toFixed(0)}<small>/100</small></strong></div></div><p className="twin-paused-note">{twin.running?'Responses are evolving together. Pause to freeze the model and compare.':'Time is frozen. Rotate the anatomy and inspect any system.'}</p></aside></div>
 <TwinHistory history={twin.history}/><footer className="twin-footer"><p>A teaching simulation, not a diagnostic tool or an exact prediction of individual physiology. Anatomical geometry is static in posture; organ motion and responses are illustrative.</p><button disabled={!twin.history.length} onClick={exportData}>Export observation data</button><a href={publicUrl('/models/open-anatomy/credits.html')} target="_blank" rel="noreferrer">3D: Z-Anatomy / BodyParts3D · Model credits</a><Link to="/living">Explore individual living organs <ArrowRight size={15}/></Link></footer></main>;
}
