import { useCallback, useEffect, useRef, useState } from 'react';
import { Link, Navigate, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Camera, Expand, Focus, Layers3, Pause, Play, RotateCcw, ScanLine, Tag, X } from 'lucide-react';
import JourneyCanvas from '../components/journey/JourneyCanvas';
import { clearModelCache } from '../hooks/useModelAsset';
import { clampDepth, journeyParts, journeyStages, stageIndex, type JourneyPath } from '../data/journey';

import { isJourneyPath, journeyRoutes, journeyStudies, studyFor } from '../data/journeyCatalog';
import JourneyKnowledgeCheck, { expandedLesson } from '../components/journey/JourneyLesson';
import JourneyLibrary from '../components/journey/JourneyLibrary';
import JourneyTopicLesson from '../components/journey/JourneyTopicLesson';
import { getJourneyTopic, journeyLibrary, journeyTopicUrl, type JourneyTopic } from '../data/journeyLibrary';
import { useJourneyProgress } from '../hooks/useJourneyProgress';
import '../styles/journeyLibrary.css';
const defaults=['body','organ','wall','membrane','mitochondrion','dna','oxygen'];
export default function Journey(){
 const {stage:routeStage}=useParams();const [query,setQuery]=useSearchParams();const navigate=useNavigate();
 const index=routeStage?stageIndex(routeStage):0;
 const topic=getJourneyTopic(query.get('journey')),progress=useJourneyProgress();
 function scaleUrl(stageId:string){const next=new URLSearchParams({path});if(topic){next.set('journey',topic.id);if(journeyStages[topic.level].id===stageId&&topic.study)next.set('study',topic.study);}return `/journey/${stageId}?${next}`;}
 function startTopic(item:JourneyTopic){reset();navigate(journeyTopicUrl(item));}
 const [depth,setDepth]=useState(Math.max(0,index));const [selected,setSelected]=useState(defaults[Math.max(0,index)]);const [scaleZoom,setScaleZoom]=useState(true);const liveDepth=useRef(depth);liveDepth.current=depth;
 const [playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[labels,setLabels]=useState(true),[transparent,setTransparent]=useState(false),[section,setSection]=useState(false),[explode,setExplode]=useState(0),[travel,setTravel]=useState(false),[travelProgress,setTravelProgress]=useState(0),[phase,setPhase]=useState(0),[fullscreen,setFullscreen]=useState(false),[error,setError]=useState(false),[viewerKey,setViewerKey]=useState(0),[notice,setNotice]=useState('');
 const viewerFailure=useCallback(()=>setError(true),[]);
 const [command,setCommand]=useState<{serial:number;view:'front'|'side'|'fit'}>({serial:0,view:'front'});
 const [isolated,setIsolated]=useState<string>(),[hidden,setHidden]=useState<string[]>([]);
 const clock=useRef(0),root=useRef<HTMLElement>(null);const requestedPath=query.get('path');const path:JourneyPath=isJourneyPath(requestedPath)?requestedPath:'blood';const route=journeyRoutes[path];
 const level=Math.round(depth),study=studyFor(level,query.get('study')??undefined),stage=expandedLesson(level,path,study?.id??''),part=journeyParts[selected];const structures=level===2?route.structures:study?.structures??[level===0?'body':'organ'];
 function view(view:'front'|'side'|'fit'){setCommand(c=>({serial:c.serial+1,view}));}
 function go(value:number){const next=clampDepth(value);navigate(scaleUrl(journeyStages[Math.round(next)].id));setDepth(next);}
 useEffect(()=>{if(index>=0){setDepth(index);setSelected(index===2?journeyRoutes[path].structures[0]:studyFor(index,query.get('study')??undefined)?.structures[0]??defaults[index]);setTravel(false);setExplode(0);clock.current=0;setPhase(0);}},[index,path,query.get('study')]);
 useEffect(()=>{setIsolated(undefined);setHidden([]);},[level,path,study?.id]);
 useEffect(()=>{const view=root.current?.querySelector('.journey-view');if(!view||!scaleZoom||travel)return;let timer=0;function wheel(event:Event){const e=event as WheelEvent;if((e.target as HTMLElement)?.closest('button'))return;e.preventDefault();e.stopPropagation();liveDepth.current=clampDepth(liveDepth.current-e.deltaY*.002);setDepth(liveDepth.current);window.clearTimeout(timer);timer=window.setTimeout(()=>navigate(scaleUrl(journeyStages[Math.round(liveDepth.current)].id)),300);}view.addEventListener('wheel',wheel,{capture:true,passive:false});return()=>{view.removeEventListener('wheel',wheel,true);window.clearTimeout(timer);};},[scaleZoom,travel,path,topic?.id,navigate]);
 useEffect(()=>{const timer=window.setInterval(()=>{setPhase((clock.current%12)/12);if(playing&&travel)setTravelProgress(Math.min(1,clock.current/20));},100);return()=>clearInterval(timer);},[playing,travel]);
 useEffect(()=>{function keys(e:KeyboardEvent){if(e.target instanceof HTMLElement&&(e.target.closest('input,select,textarea,button,a')||e.target.isContentEditable))return;if(e.key==='ArrowRight'){e.preventDefault();go(level+1);}if(e.key==='ArrowLeft'){e.preventDefault();go(level-1);}if(e.code==='Space'){e.preventDefault();setPlaying(p=>!p);}}window.addEventListener('keydown',keys);return()=>window.removeEventListener('keydown',keys);},[level,path,topic?.id]);
 useEffect(()=>{const change=()=>setFullscreen(document.fullscreenElement===root.current);document.addEventListener('fullscreenchange',change);return()=>document.removeEventListener('fullscreenchange',change);},[]);
 async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await root.current?.requestFullscreen();}catch{setNotice('Fullscreen is unavailable in this browser.');}}
 function reset(){setPlaying(false);setTravel(false);setTravelProgress(0);setTransparent(false);setSection(false);setExplode(0);setIsolated(undefined);setHidden([]);clock.current=0;setPhase(0);view('front');}
 function screenshot(){const canvas=root.current?.querySelector('canvas');if(!canvas)return;try{const link=document.createElement('a');link.download=`human-atlas-journey-${stage.id}.png`;link.href=canvas.toDataURL('image/png');link.click();setNotice('3D screenshot saved.');}catch{setNotice('Screenshot is unavailable.');}}
 if(index<0)return <Navigate to="/journey/body" replace/>;
 return <main id="main" ref={root} className={`journey-page ${fullscreen?'journey-fullscreen':''}`}>
  <header className="journey-heading"><div><Link to="/" className="journey-back"><ArrowLeft size={14}/> Human Atlas</Link><h1>Journey Inside the Human Body</h1><p>{journeyLibrary.length} guided journeys. Seven scales. Search your next discovery.</p></div><div className="journey-route"><label htmlFor="journey-path">Core 3D route</label><select id="journey-path" value={path} onChange={e=>{setQuery({path:e.target.value});reset();}}>{Object.entries(journeyRoutes).map(([id,item])=><option key={id} value={id}>{item.name}</option>)}</select></div></header>
  <JourneyLibrary active={topic?.id} saved={progress.saved} completed={progress.completed} onToggle={progress.toggle} onStart={startTopic}/>
  {topic&&<div className="journey-active-topic"><div><span className="eyebrow">CURRENT GUIDED JOURNEY</span><strong>{topic.title}</strong><small>{topic.category} · {progress.completed.includes(topic.id)?'Studied':'In progress'}</small></div><button onClick={()=>{const next=new URLSearchParams(query);next.delete('journey');setQuery(next);}}>Leave guided topic <X size={14}/></button></div>}
  {study&&<label className="journey-quick-lab">Explore this scale<select aria-label="Viewer lab" value={study.id} onChange={e=>{setQuery({path,study:e.target.value,...(topic?{journey:topic.id}:{})});reset();}}>{journeyStudies[level].map(lab=><option key={lab.id} value={lab.id}>{lab.name}</option>)}</select></label>}
  <nav className="journey-scales" aria-label="Journey scale navigation">{journeyStages.map((s,i)=><Link key={s.id} to={scaleUrl(s.id)} aria-current={i===level?'step':undefined}><span>0{i+1}</span>{s.name}</Link>)}</nav>
  <div className="journey-workspace">
   <section className="journey-view" aria-label="3D exploration">
    <div className="journey-view-status"><span><i/>{stage.name.toUpperCase()} / {route.name.toUpperCase()}</span><small>{stage.scale}</small></div>
    <JourneyCanvas key={viewerKey} depth={depth} path={path} study={study?.id??''} selected={selected} onSelect={setSelected} labels={labels} transparent={transparent} section={section} explode={explode} playing={playing} speed={speed} clock={clock} isolated={isolated} hidden={hidden} travel={travel} travelProgress={travelProgress} command={command} onError={viewerFailure}/>
    <button className="journey-view-play" aria-label={playing?'Pause animation':'Play animation'} onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'Pause':'Observe process'}</button>
    {error&&<div className="journey-retry"><button onClick={()=>{for(const model of ['body',route.model])clearModelCache(model);setViewerKey(k=>k+1);setError(false);}}>Retry 3D viewer</button></div>}
    <div className="journey-view-hint">{travel?'Inside travel · use the route slider':`Drag to orbit · scroll to ${scaleZoom?'travel between scales':'zoom the camera'} · click to select`}</div>
    <div className="journey-toolbar" aria-label="3D tools">
     <button aria-pressed={scaleZoom} onClick={()=>setScaleZoom(v=>!v)} title="Switch between scale travel and camera zoom">Scale zoom</button><button onClick={()=>{setTravel(false);view('front');}} title="Front view">Front</button><button onClick={()=>{setTravel(false);view('side');}} title="Side view">Side</button><button onClick={()=>{setTravel(false);view('fit');}} title="Fit selected structure"><Focus size={16}/><span>Focus</span></button>
     <button aria-pressed={labels} onClick={()=>setLabels(v=>!v)} title="Toggle labels"><Tag size={16}/><span>Labels</span></button><button aria-pressed={transparent} onClick={()=>setTransparent(v=>!v)} title="Toggle transparency"><Layers3 size={16}/><span>Transparent</span></button><button aria-pressed={section} onClick={()=>setSection(v=>!v)} title="Cut away front half"><ScanLine size={16}/><span>Section</span></button>
     <button onClick={reset} title="Reset current scene"><RotateCcw size={16}/><span>Reset</span></button><button onClick={screenshot} title="Save 3D screenshot"><Camera size={16}/><span>Capture</span></button><button onClick={()=>void toggleFullscreen()} title={fullscreen?'Exit fullscreen':'Enter fullscreen'}>{fullscreen?<X size={16}/>:<Expand size={16}/>}<span>Fullscreen</span></button>
    </div>
   </section>
   <aside className="journey-info" aria-label="Scale explanation">{topic&&<JourneyTopicLesson topic={topic} saved={progress.saved.includes(topic.id)} completed={progress.completed.includes(topic.id)} onToggle={progress.toggle} onReturn={()=>startTopic(topic)}/>}<div className="eyebrow">LEVEL 0{level+1} · {stage.name.toUpperCase()}</div><h2>{stage.title}</h2><p>{stage.description}</p>
    {study&&<label className="journey-study-select">Choose a microscopic lab<select aria-label="Microscopic lab" value={study.id} onChange={e=>{setQuery({path,study:e.target.value,...(topic?{journey:topic.id}:{})});reset();}}>{journeyStudies[level].map(lab=><option key={lab.id} value={lab.id}>{lab.name}</option>)}</select></label>}
    <div className="journey-structure-list" aria-label="Selectable structures">{structures.map(id=><button key={id} aria-pressed={selected===id} onClick={()=>setSelected(id)}>{id==='organ'?route.organ:journeyParts[id].name}</button>)}</div>
    <div className="journey-selected"><small>SELECTED STRUCTURE</small><h3>{selected==='organ'?route.organ:part?.name}</h3><p>{part?.description}</p><div className="journey-selection-actions"><button onClick={()=>{setTravel(false);view('fit');}}>Focus <Focus size={14}/></button><button aria-pressed={isolated===selected} onClick={()=>{setIsolated(isolated===selected?undefined:selected);setHidden(h=>h.filter(id=>id!==selected));}}>Isolate</button><button onClick={()=>setHidden(h=>h.includes(selected)?h.filter(id=>id!==selected):[...h,selected])}>{hidden.includes(selected)?'Show':'Hide'}</button>{(isolated||hidden.length>0)&&<button onClick={()=>{setHidden([]);setIsolated(undefined);}}>Show all</button>}</div></div>
    {level===2&&<div className="journey-travel"><button aria-pressed={travel} onClick={()=>{setTravel(v=>!v);clock.current=0;setTravelProgress(0);view('front');}}>{travel?'Leave inside travel':route.travelName} <ArrowRight size={15}/></button>{travel&&<label>Route position <input aria-label="Travel position" type="range" min="0" max="1" step=".01" value={travelProgress} onChange={e=>{const value=Number(e.target.value);setTravelProgress(value);clock.current=value*20;}}/><small>{Math.round(travelProgress*100)}% · {travelProgress>=1?'Route complete — restart to travel again':playing?'Travelling':'Press play to travel'}</small></label>}</div>}
    {level>=3&&<label className="journey-explode">Separate the assembly <input type="range" aria-label="Assembly separation" min="0" max="1" step=".01" value={explode} onChange={e=>setExplode(Number(e.target.value))}/><span><button onClick={()=>setExplode(explode?0:1)}>{explode?'Assemble':'Explode'}</button><small>{Math.round(explode*100)}%</small></span></label>}
    <details className="journey-process" open><summary>{stage.process}</summary><ol>{stage.steps.map((step,i)=><li key={step} className={playing&&Math.floor(phase*3)===i?'current':''}>{step}</li>)}</ol></details>
    <JourneyKnowledgeCheck key={path} path={path}/>
    <div className="journey-quality"><strong>{level<2?'Anatomy overview':'Interactive 3D teaching model'}</strong><p>Explore with Human Atlas by VisionariesAI Labs. Microscopic geometry and animation illustrate biological concepts; they are not a scan through one person or a physiological calculation.{section?' Section mode clips surfaces without reconstructing tissue at the cut.':''}</p></div>
   </aside>
  </div>
  <footer className="journey-footer"><div className="journey-play"><button aria-label={playing?'Pause process':'Play process'} onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={19}/>:<Play size={19}/>}</button><div><strong>{stage.process}</strong><small>{playing?'Animation playing':'Paused · press play to observe'}</small></div><label>Speed<select aria-label="Animation speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={.5}>0.5×</option><option value={1}>1×</option><option value={2}>2×</option></select></label><button aria-label="Restart process" onClick={()=>{clock.current=0;setTravelProgress(0);setPhase(0);}}><RotateCcw size={16}/></button></div><div className="journey-timeline"><label htmlFor="journey-process-position">Process timeline <small>{Math.round(phase*100)}%</small></label><input id="journey-process-position" type="range" min="0" max="1" step=".01" value={phase} onChange={e=>{setPlaying(false);clock.current=Number(e.target.value)*11.999;setPhase(Number(e.target.value));}}/></div><div className="journey-depth"><label htmlFor="journey-depth">Travel between scales <small>{stage.name}</small></label><input id="journey-depth" type="range" min="0" max="6" step=".01" value={depth} onChange={e=>setDepth(clampDepth(Number(e.target.value)))} onPointerUp={()=>go(Math.round(depth))} onKeyUp={()=>go(Math.round(depth))}/></div><div className="journey-next"><button aria-label="Previous scale" disabled={level===0} onClick={()=>go(level-1)}><ArrowLeft size={17}/></button><button disabled={level===6} onClick={()=>go(level+1)}>{level===6?'Journey complete':'Go deeper'} <ArrowRight size={17}/></button></div></footer>
  {notice&&<div role="status" className="journey-notice">{notice}<button aria-label="Dismiss message" onClick={()=>setNotice('')}><X size={14}/></button></div>}
 </main>;
}
