import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, ArrowRight, BookOpen, Monitor, Pause, Play, RotateCcw, X } from 'lucide-react';
import { useAtlasStore } from '../../store/atlasStore';
import { learningLevels, ANATOMY_ZOOM, type LearningLevel } from '../../config/education';
import { anatomy, isWithin } from '../../data/anatomyTree';
import { anatomyModels } from '../../data/modelRegistry';
import { lessons } from '../../data/lessons';
import BodyFacts from '../atlas/BodyFacts';
export default function SchoolControls({onPresentation}:{onPresentation:()=>void}){
 const s=useAtlasStore(),navigate=useNavigate();const [panel,setPanel]=useState(false),[overview,setOverview]=useState(false),[lesson,setLesson]=useState('muscles'),[step,setStep]=useState(0),[playing,setPlaying]=useState(false);
 function go(index:number){const sequence=lessons[lesson].steps;const next=Math.max(0,Math.min(sequence.length-1,index));setStep(next);const item=sequence[next];if(item.route)navigate(`${item.route}${anatomyModels[s.activeModel]?.root===item.id?'':`/${item.id}`}`.replace(/\/body\/body$/,'/body'));else if(isWithin(item.id,anatomyModels[s.activeModel].root))s.select(item.id);else navigate(`/atlas/body/${item.id}`);}
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>{if(step>=lessons[lesson].steps.length-1)setPlaying(false);else go(step+1);},6500/s.motionSpeed);return()=>clearInterval(timer);},[playing,step,lesson,s.motionSpeed]);
 function back(){s.set('autoSeparate',false);s.setExplosion(0);s.set('activeRegion',null);s.set('autoSeparation',0);s.reset();if(anatomyModels[s.activeModel].root!=='body')navigate('/atlas/body');}
 return <><div className="school-controls"><label>Learning level<select aria-label="Learning level" value={s.learningLevel} onChange={e=>s.set('learningLevel',e.target.value as LearningLevel)}>{Object.entries(learningLevels).map(([id,l])=><option key={id} value={id}>{l.name}</option>)}</select></label><button disabled={!s.viewHistory.length} onClick={s.backView} title="Restore previous selection and camera">Back</button><button onClick={back}><ArrowLeft size={14}/> Back to Body</button><button onClick={()=>{s.set('autoSeparate',false);s.set('autoSeparation',0);s.setExplosion(0);}}><RotateCcw size={14}/> Assemble Body</button>{s.systemFilter==='muscular'&&<button aria-pressed={s.autoSeparate} onClick={()=>s.set('autoSeparate',!s.autoSeparate)}>Auto separate {s.autoSeparate?'on':'off'}</button>}<button onClick={()=>setPanel(!panel)} aria-expanded={panel}><BookOpen size={14}/> Guided paths</button>{s.systemFilter==='cardiovascular'&&<><button aria-pressed={s.flowEnabled} onClick={()=>{s.set('flowEnabled',!s.flowEnabled);s.set('motionPlaying',true);}}>Blood Flow</button>{s.flowEnabled&&<button onClick={()=>s.set('motionPlaying',!s.motionPlaying)}>{s.motionPlaying?'Pause flow':'Play flow'}</button>}</>}<button onClick={()=>setOverview(!overview)}>Body overview</button><button onClick={onPresentation}><Monitor size={14}/>{s.presentation?'Exit Presentation':'Start Classroom Demo'}</button></div><div className="semantic-readout">{s.flowEnabled&&<span>Schematic flow order · blue: oxygen-poor, red: oxygen-rich · not a vessel path</span>}<span>{ANATOMY_ZOOM.find(z=>z.id===s.semanticDepth)?.name}</span>{s.autoSeparation>0&&<span>Regional separation {Math.round(s.autoSeparation*100)}%</span>}{s.semanticDepth==='MICRO'&&<button onClick={()=>navigate(s.systemFilter==='respiratory'?'/atlas/alveolus':s.systemFilter==='urinary'?'/atlas/nephron':s.systemFilter==='cardiovascular'?'/atlas/capillary':'/atlas/neuron')}>Open microscopic concept →</button>}</div>
 {panel&&<div className="teaching-panel"><div><strong>Guided learning</strong><button aria-label="Close guided learning" onClick={()=>setPanel(false)}><X size={17}/></button></div><select aria-label="Choose lesson" value={lesson} onChange={e=>{setLesson(e.target.value);setStep(0);setPlaying(false);}}>{Object.entries(lessons).map(([id,l])=><option key={id} value={id}>{l.title}</option>)}</select><small>Step {step+1} of {lessons[lesson].steps.length}</small><h3>{lessons[lesson].steps[step].title}</h3><p>{lessons[lesson].steps[step].explanation}</p><div className="lesson-buttons"><button disabled={!step} onClick={()=>go(step-1)} aria-label="Previous lesson step"><ArrowLeft size={18}/></button><button onClick={()=>go(step)}>Focus step</button><button onClick={()=>{if(!playing)go(step);setPlaying(!playing);}} aria-label={playing?'Pause lesson':'Play lesson'}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><button disabled={step===lessons[lesson].steps.length-1} onClick={()=>go(step+1)} aria-label="Next lesson step"><ArrowRight size={18}/></button></div><label>Playback speed<select value={s.motionSpeed} aria-label="Lesson speed" onChange={e=>s.set('motionSpeed',+e.target.value)}><option value=".5">Slow</option><option value="1">Normal</option></select></label></div>}
 {overview&&<div className="overview-sheet" role="dialog" aria-modal="false" aria-label="Human body overview"><button className="icon-btn" aria-label="Close body overview" onClick={()=>setOverview(false)}><X/></button><BodyFacts/></div>}</>;
}

