import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowUpRight, Search, X } from 'lucide-react';
import { searchAnatomy, getAncestors } from '../../data/anatomyTree';
import { systems } from '../../data/modelRegistry';
import { anatomyRoute } from '../../data/anatomyRoutes';
import { biologyModules } from '../../data/biology';
import { virtualLabs } from '../../data/virtualLabs';
export default function SearchDialog({open,onClose,onOpen}:{open:boolean;onClose:()=>void;onOpen:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);const [query,setQuery]=useState('');const [index,setIndex]=useState(0);const navigate=useNavigate();const systemResults=query?systems.filter(s=>s.name.toLowerCase().includes(query.toLowerCase())).map(s=>({id:`system:${s.id}`,name:s.name,system:'Body system'})):[];const biologyResults=query?[...biologyModules.filter(module=>`${module.title} ${module.subject} ${module.overview} class ${module.classLevel}`.toLowerCase().includes(query.toLowerCase())).map(module=>({id:`biology:${module.id}`,name:module.title,system:`${module.subject} · Class ${module.classLevel}`})),...virtualLabs.filter(lab=>lab.title.toLowerCase().includes(query.toLowerCase())).map(lab=>({id:`lab:${lab.id}`,name:lab.title,system:'Virtual laboratory'}))]:[];const twinResults=query&&/digital|twin|exercise|living human/i.test(query)?[{id:'twin',name:'Biology Digital Twin',system:'Connected exercise teaching simulation'}]:[];const results=[...twinResults,...systemResults,...biologyResults,...searchAnatomy(query)].slice(0,10);
 useEffect(()=>{if(open){ref.current?.showModal();setQuery('');setIndex(0);}else ref.current?.close();},[open]);
 useEffect(()=>{const listener=(e:KeyboardEvent)=>{if(document.fullscreenElement&&!document.fullscreenElement.contains(ref.current))return;if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();onOpen();}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[onOpen]);
 function choose(id:string){onClose();navigate(id==='twin'?'/digital-twin':id.startsWith('biology:')?`/biology/module/${id.slice(8)}`:id.startsWith('lab:')?`/labs/${id.slice(4)}`:id.startsWith('system:')?`/systems/${id.slice(7)}`:anatomyRoute(id));}
 return <dialog ref={ref} className="search-dialog" aria-label="Search anatomy" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="search-input-row"><Search size={21}/><input autoFocus value={query} placeholder="Find anatomy, biology or a virtual lab…" aria-label="Search anatomical structures" role="combobox" aria-expanded="true" aria-controls="search-results" aria-activedescendant={results[index]?`result-${results[index].id}`:undefined} onChange={e=>{setQuery(e.target.value);setIndex(0);}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setIndex(i=>Math.min(i+1,results.length-1));}if(e.key==='ArrowUp'){e.preventDefault();setIndex(i=>Math.max(0,i-1));}if(e.key==='Enter'&&results[index]){e.preventDefault();choose(results[index].id);}}}/><button className="icon-btn" onClick={onClose} aria-label="Close search"><X size={18}/></button></div><div className="search-caption">{query?'MATCHING RESULTS':'EXPLORE THE ANATOMY'}</div><div id="search-results" role="listbox">{results.map((n,i)=><button role="option" aria-selected={i===index} id={`result-${n.id}`} key={n.id} className={`search-result ${i===index?'active':''}`} onClick={()=>choose(n.id)} onMouseEnter={()=>setIndex(i)}><span className="result-icon"><Search size={17}/></span><span><strong>{n.name}</strong><small>{n.system} · {n.id==='twin'?'Connected simulation':n.id.startsWith('biology:')?'Biology module':n.id.startsWith('lab:')?'Virtual experiment':getAncestors(n.id).slice(0,-1).map(a=>a.name).join(' / ')||'Complete atlas'}</small></span><ArrowUpRight size={18}/></button>)}{results.length===0&&<div className="empty-state">No structures found. Try “heart”, “brain”, or “bones”.</div>}</div><div className="search-footer"><span>↑ ↓ to navigate</span><span>Enter to explore</span><kbd>Esc to close</kbd></div></dialog>;
}
