import type { JourneyPath } from './journey';
import { journeyStages } from './journey';
import { journeyRoutes, studyFor } from './journeyCatalog';

export type JourneyTopic = {
 id:string; title:string; category:string; description:string; takeaway:string;
 path:JourneyPath; level:number; study?:string; difficulty:'Foundation'|'Intermediate'|'Advanced';
};
type Entry = [title:string, description:string, takeaway:string, level?:number, study?:string];
type Collection = {category:string; path:JourneyPath; entries:Entry[]};

// Topics have their own lessons and reuse the named teaching scenes; they are not 120 unique anatomy assets.
const collections:Collection[] = [
 {category:'Cardiovascular',path:'blood',entries:[
  ['Through the heart','Follow the relationship between the heart’s chambers and forward blood flow.','Valves support directional flow as pressure differences change.',1],
  ['Inside an artery','Connect arterial walls with the pressure generated by the heart.','Elastic and muscular wall components help arteries accommodate and regulate flow.',2],
  ['The venous return','Explore how blood returns from tissues towards the heart.','Venous valves and surrounding muscle activity assist return; pressure drives movement.',2],
  ['Capillary exchange','Consider the thin boundary between circulating blood and surrounding tissue.','Small vessels provide short diffusion distances for exchange.',2],
  ['A red blood cell’s journey','Inspect the biconcave cell that transports respiratory gases.','Mature human red blood cells lack nuclei and carry hemoglobin.',2],
  ['The vessel-wall cell','Move from a vessel to the cellular boundary controlling exchange.','Endothelial cells form the inner lining of blood vessels.',3,'transport'],
  ['Oxygen delivery to tissues','Connect oxygen transport in blood with its use by cells.','Oxygen delivery depends on both blood flow and blood oxygen content.',6,'oxygen-molecule'],
  ['Cardiac energy demand','Study the organelle machinery supporting repeated contraction.','Cardiac cells rely strongly on aerobic ATP production.',4,'mitochondrion']
 ]},
 {category:'Nervous',path:'neuron',entries:[
  ['From brain to neuron','Move from brain anatomy to a representative nerve cell.','Neural networks combine receiving, processing and transmitting signals.',1],
  ['Dendrites receive signals','Explore the branched receiving region of a neuron.','Dendrites and the soma integrate inputs from other cells.',2],
  ['Along an axon','Follow the direction of action-potential propagation.','A signal travels as changing membrane voltage, not as one particle moving end to end.',2],
  ['Myelin and conduction','Relate insulating segments to efficient electrical signalling.','Myelin changes how current spreads and supports saltatory conduction.',2],
  ['Ion channels in neurons','Use the membrane scene to reason about selective ion movement.','Channel opening changes membrane permeability and therefore electrical activity.',3,'transport'],
  ['Synaptic protein production','Explore how neurons manufacture proteins used in communication.','RNA messages guide ribosomes in assembling polypeptides.',3,'translation'],
  ['Axonal energy supply','Connect neural activity with mitochondrial energy production.','Maintaining ion gradients consumes ATP.',4,'mitochondrion'],
  ['Neural gene expression','Study how a neuron uses DNA information to produce RNA.','Cell identity depends partly on which genes are expressed.',5,'transcription']
 ]},
 {category:'Respiratory',path:'respiratory',entries:[
  ['From lungs to alveoli','Travel from the lung surface towards an air–blood interface.','Alveoli provide a large exchange surface within the lungs.',1],
  ['An alveolar air space','Inspect the relationship between an air space and nearby blood vessels.','A thin respiratory barrier separates air from capillary blood.',2],
  ['Oxygen crosses the barrier','Follow the oxygen teaching markers towards blood.','Oxygen diffuses according to a partial-pressure difference.',2],
  ['Carbon dioxide leaves blood','Follow the reverse direction of respiratory gas exchange.','Carbon dioxide diffuses towards alveolar air before exhalation.',2],
  ['The capillary around an alveolus','Examine how blood flow meets the respiratory surface.','Ventilation and perfusion must work together for effective exchange.',2],
  ['Respiratory epithelial cells','Explore a generalized cell as a comparison for the alveolar lining.','Specialized alveolar cells contribute to barrier structure and surfactant production.',3,'transport'],
  ['Meet molecular oxygen','Inspect the two atoms forming an oxygen molecule.','Oxygen is used in aerobic cellular energy pathways.',6,'oxygen-molecule'],
  ['Meet carbon dioxide','Inspect a linear molecule returned to the lungs from metabolism.','Carbon dioxide has one carbon atom and two oxygen atoms.',6,'carbon-dioxide']
 ]},
 {category:'Digestive',path:'digestive',entries:[
  ['Into the small intestine','Connect intestinal anatomy with digestion and absorption.','The small intestine is a major site of nutrient absorption.',1],
  ['A villus from the inside','Explore the cellular covering and vessels of an intestinal projection.','Villi increase the available absorptive surface.',2],
  ['Microvilli and surface area','Relate tiny epithelial projections to nutrient uptake.','Microvilli increase cell surface area at the intestinal lumen.',2],
  ['Nutrients enter blood','Follow a capillary pathway through a villus.','Many absorbed sugars and amino acids enter blood pathways.',2],
  ['Lipids enter lymph','Inspect the central lacteal within a villus.','Many absorbed dietary lipids are transported through lymph as chylomicrons.',2],
  ['The absorptive cell','Inspect the compartments of a generalized intestinal comparison cell.','Transport across epithelium involves distinct apical and basolateral surfaces.',3,'transport'],
  ['Digestive enzyme synthesis','Connect protein synthesis with enzyme production.','Secreted protein products enter processing and transport pathways.',3,'translation'],
  ['Glucose after absorption','Zoom into the molecular composition of a common dietary sugar.','Glucose can supply substrates for cellular energy production.',6,'glucose']
 ]},
 {category:'Urinary',path:'renal',entries:[
  ['From kidney to nephron','Connect the kidney overview with a functional filtration unit.','Nephrons filter blood and modify the resulting fluid.',2],
  ['Inside the glomerulus','Inspect the capillary tuft where filtration starts.','Fluid crosses a filtration barrier into the capsular space.',2],
  ['The glomerular capsule','Identify the receiving compartment around the capillary tuft.','Filtrate enters the tubule from the capsule.',2],
  ['Following a renal tubule','Travel along the schematic tubular pathway.','Reabsorption and secretion alter filtrate composition.',2],
  ['The collecting pathway','Inspect where modified tubular fluid continues towards excretion.','Collecting ducts participate in regulating final water handling.',2],
  ['Tubular transport cells','Study a generalized cell boundary supporting selective transport.','Renal epithelial cells use transport proteins to move selected substances.',3,'transport'],
  ['Energy for reabsorption','Relate mitochondrial activity to ATP-dependent tubular transport.','Active transport requires energy supplied by cellular metabolism.',4,'mitochondrion'],
  ['Water in renal balance','Inspect water before connecting its movement to fluid regulation.','Osmotic gradients and membrane permeability influence water movement.',6,'water']
 ]},
 {category:'Muscular',path:'muscle',entries:[
  ['From muscle to sarcomere','Connect whole-muscle anatomy to its repeating contractile units.','Sarcomeres form the repeating units of striated myofibrils.',1],
  ['Actin’s role in contraction','Inspect thin filaments in a schematic sarcomere.','Thin filaments interact with myosin during contraction.',2],
  ['Myosin motor activity','Explore thick filaments and their relationship to actin.','ATP-dependent myosin cycling generates force.',2],
  ['Z discs move together','Follow the boundaries of a shortening sarcomere.','Filament lengths stay similar while overlap and sarcomere length change.',2],
  ['Calcium and contraction','Use the contractile assembly to discuss activation of binding sites.','Calcium binds troponin in striated muscle, altering regulation of actin–myosin interaction.',2],
  ['Muscle protein synthesis','Relate translation to maintenance of contractile proteins.','Ribosomes assemble the polypeptides that contribute to muscle structure.',3,'translation'],
  ['Mitochondria in active muscle','Explore energy machinery supporting repeated force production.','Oxidative metabolism contributes ATP during sustained activity.',4,'mitochondrion'],
  ['Glucose as muscle fuel','Inspect a fuel molecule used by muscle energy pathways.','Muscle can use several fuels; glucose is one important substrate.',6,'glucose']
 ]},
 {category:'Skeletal & connective tissue',path:'muscle',entries:[
  ['A bone-building cell','Use a generalized cell to study the work of an osteoblast.','Osteoblasts produce bone matrix and support its mineralization.',3,'transport'],
  ['Bone matrix protein production','Connect translation with collagen production.','Collagen is an important organic component of bone matrix.',3,'translation'],
  ['Osteocyte communication','Consider how embedded bone cells sense their surroundings.','Osteocytes communicate through processes extending within canaliculi.',3,'transport'],
  ['Bone remodelling and recycling','Use the lysosome lab to discuss intracellular breakdown.','Bone remodelling coordinates matrix resorption and new bone formation.',4,'lysosome'],
  ['Cartilage-producing cells','Compare a generalized cell with a cartilage-maintaining chondrocyte.','Chondrocytes maintain the specialized extracellular matrix of cartilage.',3,'transport'],
  ['Tendon protein assembly','Follow protein synthesis as a foundation for connective tissue.','Collagen-rich tendons transmit force between muscle and bone.',3,'translation'],
  ['Growth and cellular division','Observe a general mitotic model before discussing tissue growth.','Mitosis increases cell numbers while preserving the chromosome complement.',3,'division'],
  ['Connective tissue secretion','Follow the ER–Golgi pathway used for secreted cellular products.','Extracellular matrix proteins require synthesis, processing and secretion.',4,'golgi']
 ]},
 {category:'Endocrine',path:'blood',entries:[
  ['Hormones reach target cells','Use a cell membrane to discuss receptor-dependent signalling.','A cell responds to a hormone only when the appropriate receptor and signalling machinery are present.',3,'transport'],
  ['Peptide hormone synthesis','Follow translation as a starting point for peptide hormone production.','Peptide hormones originate from protein synthesis pathways.',3,'translation'],
  ['Secretory vesicle packaging','Inspect how cellular products are sorted into vesicles.','Regulated secretion can release stored products following a stimulus.',4,'golgi'],
  ['The endocrine cell’s ER','Explore membranes involved in synthesis and processing.','Rough ER participates in production of many secreted proteins.',4,'reticulum'],
  ['Steroid signals and gene expression','Connect intracellular signalling with RNA production.','Many steroid hormone receptors regulate transcription after binding their ligand.',5,'transcription'],
  ['Insulin and glucose uptake','Compare a glucose model with its movement into responsive tissues.','Insulin supports glucose uptake in skeletal muscle and adipose tissue.',6,'glucose'],
  ['Feedback and cellular response','Examine a comparison cell while discussing endocrine feedback.','Negative feedback helps regulate many hormone pathways.',3,'transport'],
  ['Energy in secretory cells','Inspect mitochondrial organization within an active cell.','Secretory activity and cellular maintenance require metabolic energy.',4,'mitochondrion']
 ]},
 {category:'Lymphatic & immune',path:'blood',entries:[
  ['Exchange and interstitial fluid','Inspect the small-vessel boundary surrounding tissues.','Lymphatic pathways return excess interstitial fluid to circulation.',2],
  ['Immune cell architecture','Explore a generalized nucleated cell as an immune-cell comparison.','Immune cells use membranes and intracellular compartments to recognize and respond to their environment.',3,'transport'],
  ['Antibody protein production','Follow translation as a foundation for antibody synthesis.','Plasma cells produce antibodies using protein-synthesis and secretion pathways.',3,'translation'],
  ['Antibody processing and export','Inspect the ER and transport compartments.','Secreted antibodies pass through cellular processing pathways.',4,'reticulum'],
  ['Packaging immune products','Follow Golgi sorting and vesicle transport.','Golgi compartments modify and sort many secreted proteins.',4,'golgi'],
  ['Intracellular cargo breakdown','Explore digestion of material delivered to lysosomal compartments.','Lysosomal enzymes participate in intracellular degradation.',4,'lysosome'],
  ['Lymphocyte proliferation','Observe mitosis as a comparison for clonal expansion.','Activated lymphocytes can divide to increase the responding cell population.',3,'division'],
  ['Dietary lipids in a lacteal','Connect an intestinal lymphatic vessel to nutrient transport.','Lacteals receive lipid-rich particles from intestinal absorption.',2]
 ]},
 {category:'Integumentary',path:'blood',entries:[
  ['The skin-cell boundary','Explore a membrane as the first step towards cellular barrier function.','Cell membranes regulate exchange; tissue barriers also depend on cell organization and junctions.',3,'transport'],
  ['Renewal of the epidermis','Observe mitosis as a foundation for epithelial renewal.','Dividing basal cells contribute to renewal of the epidermis.',3,'division'],
  ['Keratin protein synthesis','Follow translation in a generalized comparison cell.','Keratin proteins contribute to the structure of epidermal cells.',3,'translation'],
  ['Skin secretory pathways','Explore cellular sorting and transport.','Secreted cellular products pass through processing and export pathways.',4,'golgi'],
  ['Melanocyte protein machinery','Connect cell organization with pigment-producing cell function.','Melanocytes produce melanin in specialized compartments; the shared lab shows general organelles.',3,'transport'],
  ['Repair and chromosome duplication','Inspect DNA replication before discussing cell proliferation.','DNA is duplicated before mitosis so daughter cells receive genetic information.',5,'replication'],
  ['Energy during tissue renewal','Explore mitochondrial organization in renewing cells.','Synthesis and maintenance use energy from cellular metabolism.',4,'mitochondrion'],
  ['Water and the skin environment','Inspect the atoms and bonds of water at molecular scale.','Water participates in the cellular environment; the outer skin barrier limits water loss.',6,'water']
 ]},
 {category:'Female reproductive',path:'blood',entries:[
  ['Ovarian cellular organization','Use a generalized cell to introduce ovarian cellular compartments.','An ovary contains multiple specialized cell types; this shared model is not an oocyte reconstruction.',3,'transport'],
  ['Follicular cell proliferation','Observe mitotic division as a comparison for follicular cell growth.','Somatic follicular cells divide by mitosis; this scene does not show oocyte meiosis.',3,'division'],
  ['Oocyte energy machinery','Study mitochondrial structure as a foundation for reproductive cell biology.','Oocytes contain mitochondria that contribute to cellular energy metabolism.',4,'mitochondrion'],
  ['Uterine tube cell transport','Explore the membrane and compartments of a comparison epithelial cell.','Cilia and smooth muscle contribute to transport within uterine tubes; cilia are not modelled here.',3,'transport'],
  ['Endometrial renewal','Use mitotic division to discuss renewal of the uterine lining.','Endometrial tissue changes under hormonal regulation.',3,'division'],
  ['Endometrial secretory activity','Explore Golgi organization as a foundation for glandular secretion.','Glandular epithelial cells process and secrete cellular products.',4,'golgi'],
  ['Reproductive gene expression','Study DNA-to-RNA information flow in a generalized cell.','Hormonal and cellular signals can alter which genes are expressed.',5,'transcription'],
  ['Mammary protein secretion','Follow protein synthesis relevant to glandular secretory cells.','Secreted proteins require coordinated synthesis and processing.',3,'translation']
 ]},
 {category:'Male reproductive',path:'blood',entries:[
  ['Testicular comparison cell','Explore cellular compartments before studying specialized testicular cells.','The testis contains germ cells and supporting somatic cells with different functions.',3,'transport'],
  ['Sertoli cell organization','Study a generalized cell as a foundation for support-cell biology.','Sertoli cells support developing germ cells; this scene does not reproduce seminiferous anatomy.',3,'transport'],
  ['Leydig cell membrane networks','Use the ER lab to introduce steroid-producing cell organization.','Smooth ER contributes to steroid synthesis in specialized cells.',4,'reticulum'],
  ['Sperm energy requirements','Inspect mitochondrial machinery as a comparison for energy supply.','Sperm mitochondria are concentrated in the midpiece; the shared lab is a single organelle.',4,'mitochondrion'],
  ['Germ-cell DNA replication','Explore DNA duplication preceding cell division.','DNA replication precedes meiosis, but this scene illustrates replication rather than meiotic segregation.',5,'replication'],
  ['Compact nuclear DNA','Explore chromatin as a starting point for understanding DNA organization.','Mature sperm use specialized DNA packaging; the shared scene shows general nucleosomes.',5,'chromatin'],
  ['Accessory gland secretion','Study Golgi sorting and transport as a foundation for secretion.','Accessory glands contribute secretions to seminal fluid.',4,'golgi'],
  ['Reproductive protein production','Follow the RNA-to-polypeptide pathway.','Translation supplies proteins used in cellular structure and function.',3,'translation']
 ]},
 {category:'Cell biology',path:'blood',entries:[
  ['A complete nucleated cell','Inspect the membrane and intracellular compartments together.','A generalized cell is a comparison model; specialized human cells differ.',3,'transport'],
  ['Selective membrane transport','Explore the boundary controlling cellular exchange.','Different substances cross membranes through different transport mechanisms.',3,'transport'],
  ['Inside the nucleus','Separate the nuclear envelope, chromatin and nucleolus.','The nucleus organizes most of the DNA in a nucleated human cell.',4,'nucleus'],
  ['Rough and smooth ER','Explore a cellular membrane network.','Rough ER associates with ribosomes; smooth ER supports other specialized tasks.',4,'reticulum'],
  ['Through the Golgi stacks','Inspect sorting compartments and transport vesicles.','Golgi processing helps direct products to their destinations.',4,'golgi'],
  ['The recycling compartment','Inspect a lysosomal boundary and its cargo.','Intracellular degradation makes some components available for reuse.',4,'lysosome'],
  ['The translation assembly','Isolate RNA, transfer RNA and ribosomal components.','Ribosomes link amino acids into polypeptides using an RNA message.',4,'ribosome'],
  ['A cell becomes two','Follow chromosome separation and emerging daughter compartments.','Mitosis and cytokinesis are distinct processes condensed into this teaching sequence.',3,'division']
 ]},
 {category:'Genetics',path:'neuron',entries:[
  ['Inside a DNA double helix','Inspect complementary strands in a schematic helix.','DNA sequence carries information; the teaching colors do not encode a real gene.',5,'transcription'],
  ['DNA to RNA information flow','Connect template DNA with an emerging RNA message.','Transcription produces RNA using DNA as a template.',5,'transcription'],
  ['At a replication fork','Inspect parental strands as the helix opens.','Strand separation permits synthesis of complementary DNA.',5,'replication'],
  ['Semiconservative replication','Compare parental strands with newly synthesized strands.','Each daughter DNA duplex retains one parental strand.',5,'replication'],
  ['DNA wrapped around histones','Inspect DNA around schematic protein cores.','Nucleosomes are units of chromatin organization.',5,'chromatin'],
  ['Nuclear chromatin organization','Explore coiled material inside a nuclear boundary.','Chromatin organization contributes to accessibility of genetic information.',4,'nucleus'],
  ['From codon to amino acid','Inspect RNA, transfer RNA and a growing polypeptide.','Transfer RNA couples codon recognition with delivery of an amino acid.',3,'translation'],
  ['Chromosomes during mitosis','Follow duplicated material as sister chromatids separate.','Sister chromatids are separated before daughter nuclei form.',3,'division']
 ]},
 {category:'Molecules & metabolism',path:'muscle',entries:[
  ['Water’s bent geometry','Inspect one oxygen and two hydrogen atoms.','Water has a bent molecular arrangement; ball sizes are illustrative.',6,'water'],
  ['Oxygen’s bonded pair','Inspect the paired oxygen atoms and bond representation.','Molecular oxygen consists of two bonded oxygen atoms and has formula O₂.',6,'oxygen-molecule'],
  ['Carbon dioxide’s linear geometry','Inspect carbon between two oxygen atoms.','Carbon dioxide is a linear molecule with formula CO₂.',6,'carbon-dioxide'],
  ['Glucose atom by atom','Select carbon, hydrogen and oxygen in a ring-form diagram.','Glucose has molecular formula C₆H₁₂O₆; this scene does not specify stereochemistry.',6,'glucose'],
  ['Fuel and mitochondrial energy','Connect absorbed nutrients to organelle energy pathways.','Mitochondrial metabolism contributes to aerobic ATP production.',4,'mitochondrion'],
  ['Cristae and membrane area','Separate the mitochondrial outer boundary and inner folds.','Cristae increase inner-membrane area for energy-related processes.',4,'mitochondrion'],
  ['Carbon dioxide from metabolism','Connect a metabolic waste molecule with respiratory removal.','Metabolic pathways generate carbon dioxide that can be carried to the lungs.',6,'carbon-dioxide'],
  ['Proteins begin as polypeptides','Observe the assembly of an amino-acid chain.','Polypeptides may require folding and processing before becoming functional proteins.',3,'translation']
 ]}
];

export const journeyLibrary:JourneyTopic[] = collections.flatMap(group=>group.entries.map(([title,description,takeaway,level=3,study])=>({
 id:title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),title,category:group.category,description,takeaway,path:group.path,level,study,
 difficulty:level>=5?'Advanced':level>=3?'Intermediate':'Foundation'
})));
// The lacteal topic uses the intestinal villus rather than the circulation scene.
journeyLibrary.find(topic=>topic.title==='Dietary lipids in a lacteal')!.path='digestive';
export const journeyCategories=collections.map(group=>group.category);
export const getJourneyTopic=(id:string|null|undefined)=>journeyLibrary.find(topic=>topic.id===id);
export function journeyTopicUrl(topic:JourneyTopic){
 const query=new URLSearchParams({path:topic.path,journey:topic.id});
 if(topic.study)query.set('study',topic.study);
 return `/journey/${journeyStages[topic.level].id}?${query}`;
}
export const topicSceneName=(topic:JourneyTopic)=>studyFor(topic.level,topic.study)?.name??journeyRoutes[topic.path].name;
export type JourneyFilters={search:string;category:string;scale:string;difficulty:string;savedOnly:boolean;completedOnly:boolean;sort:'recommended'|'title'};
export function filterJourneyTopics(filters:JourneyFilters,saved:string[]=[],completed:string[]=[]){
 const words=filters.search.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
 const result=journeyLibrary.filter(topic=>
  (filters.category==='all'||topic.category===filters.category)&&
  (filters.scale==='all'||topic.level===Number(filters.scale))&&
  (filters.difficulty==='all'||topic.difficulty===filters.difficulty)&&
  (!filters.savedOnly||saved.includes(topic.id))&&(!filters.completedOnly||completed.includes(topic.id))&&
  words.every(word=>`${topic.title} ${topic.category} ${topic.description} ${topic.takeaway} ${topicSceneName(topic)}`.toLocaleLowerCase().includes(word))
 );
 return filters.sort==='title'?[...result].sort((a,b)=>a.title.localeCompare(b.title)):result;
}
